source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

# Our Libraries
def libraries
  pod 'Moya-ObjectMapper', :path => "../"
  pod 'Moya-ObjectMapper/ReactiveCocoa', :path => "../"
  pod 'Moya-ObjectMapper/RxSwift', :path => "../"
end

# Test Libraries
def test_pods
  pod 'Quick'
  pod 'Nimble'
  pod 'OHHTTPStubs'
end

target 'Demo' do
  platform :ios, '9.0'
  libraries
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '2.3'
    end
  end
end
