# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Demo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Demo
  pod 'Moya-ObjectMapper', :path => "../"
  #pod 'Moya-ObjectMapper/ReactiveCocoa', :path => "../"
  pod 'Moya-ObjectMapper/RxSwift', :path => "../"
  pod 'ObjectMapper', '~> 2.2'
  pod 'Moya'
  #pod 'Moya/ReactiveCocoa'
  pod 'Moya/RxSwift'
  #pod 'ReactiveSwift'
  #pod 'ReactiveCocoa'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxOptional'

end
